monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/api/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 60
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
