nelmio_api_doc:
    documentation:
        info:
            title: Mon Club API
            description: API for Mon Club web application
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/swagger) # Accepts routes under /api except /api/doc
