
# Password blacklist
rollerworks_password_strength:
    blacklist:
        default_provider: rollerworks_password_strength.blacklist.provider.sqlite
        providers:
            sqlite:
                dsn: "sqlite:%kernel.root_dir%/../ressources/password_blacklist.db"