vich_uploader:
    db_driver: orm

    mappings:
        doc:
            uri_prefix: /document
            upload_destination: '%kernel.project_dir%/resources/document'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: namer.directory_namer
            namer: namer.file_namer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true