vich_uploader:
    db_driver: orm

    mappings:
        doc:
            uri_prefix: /document
            upload_destination: '%kernel.project_dir%/ressources/document'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true