version: '3'
services:
  dev_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes: 
      - ../:/app:rw
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app_net

networks:
  app_net:
      driver: "bridge"